---
kind: pipeline
type: docker
name: deploy-eyeear-audiobook

steps:
  - name: install-dependencies
    image: node:20-alpine
    commands:
      - npm ci
    when:
      event:
        - push
        - pull_request

  - name: build-frontend
    image: node:20-alpine
    commands:
      - npm run build:react
      - ls -la dist/
    depends_on:
      - install-dependencies
    when:
      event:
        - push
        - pull_request

  - name: test-backend
    image: node:20-alpine
    commands:
      - apk add --no-cache curl
      - npm run dev:backend &
      - sleep 5
      - curl -f http://localhost:3003/api/health || exit 1
      - pkill -f "node.*server.js" || true
    depends_on:
      - install-dependencies
    when:
      event:
        - push
        - pull_request

  - name: deploy-to-server
    image: alpine/git:latest
    environment:
      SSH_KEY:
        from_secret: ssh_key
      DEPLOY_HOST:
        from_secret: deploy_host
      DEPLOY_USER:
        from_secret: deploy_user
      DEPLOY_PATH:
        from_secret: deploy_path
    commands:
      - apk add --no-cache openssh-client rsync
      - mkdir -p ~/.ssh
      - echo "$$SSH_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keyscan -H $$DEPLOY_HOST >> ~/.ssh/known_hosts 2>/dev/null || true
      - |
        echo "🚀 Deploying EyeEar Audiobook to $$DEPLOY_HOST..."
        
        # Create deployment directory (Drone CI creates it automatically)
        ssh -o StrictHostKeyChecking=no $$DEPLOY_USER@$$DEPLOY_HOST \
          "mkdir -p $$DEPLOY_PATH && echo 'Directory created/verified: $$DEPLOY_PATH'"
        
        # Build Docker image on server (simpler than transferring)
        echo "📦 Building Docker image on server..."
        rsync -avz --exclude='node_modules' --exclude='.git' --exclude='dist' \
          . \
          $$DEPLOY_USER@$$DEPLOY_HOST:$$DEPLOY_PATH/build/
        
        # Copy built frontend
        rsync -avz --delete \
          dist/ \
          $$DEPLOY_USER@$$DEPLOY_HOST:$$DEPLOY_PATH/build/dist/
        
        # Build image and deploy
        ssh $$DEPLOY_USER@$$DEPLOY_HOST "cd $$DEPLOY_PATH/build && docker build -t eyeear-audiobook:latest . && cd $$DEPLOY_PATH && (docker compose down 2>/dev/null || docker-compose down 2>/dev/null || true)"
        
        # Deploy docker-compose.yml
        echo "📦 Deploying docker-compose.yml..."
        rsync -avz \
          docker-compose.yml \
          $$DEPLOY_USER@$$DEPLOY_HOST:$$DEPLOY_PATH/
        
        # Start container (try docker compose v2 first, fallback to docker-compose v1)
        echo "📦 Starting Docker container..."
        ssh $$DEPLOY_USER@$$DEPLOY_HOST "cd $$DEPLOY_PATH && (docker compose up -d && docker compose ps) || (docker-compose up -d && docker-compose ps)"
        
        # Wait for service to be ready
        echo "⏳ Waiting for backend to be ready..."
        sleep 10
        
        # Health check
        echo "🏥 Running health check..."
        ssh $$DEPLOY_USER@$$DEPLOY_HOST "docker exec eyeear-backend wget -q -O- http://localhost:3003/api/health || curl -f http://localhost:3003/api/health || exit 1"
        
        echo "✅ Deployment complete!"
    depends_on:
      - build-frontend
    when:
      event:
        - push
      branch:
        - main
        - master

  - name: health-check
    image: alpine/curl:latest
    environment:
      DEPLOY_HOST:
        from_secret: deploy_host
    commands:
      - |
        echo "🏥 Running post-deployment health check..."
        sleep 10
        curl -f https://$$DEPLOY_HOST/api/health || \
        curl -f http://$$DEPLOY_HOST/api/health || \
        echo "⚠️  Health check failed, but deployment may still be in progress"
    depends_on:
      - deploy-to-server
    when:
      event:
        - push
      branch:
        - main
        - master

  - name: notify-deployment
    image: alpine/curl:latest
    environment:
      DEPLOY_HOST:
        from_secret: deploy_host
    commands:
      - |
        echo "📢 Deployment notification"
        echo "✅ EyeEar Audiobook deployed successfully!"
        echo "🌐 URL: https://$$DEPLOY_HOST"
        echo "🔗 API: https://$$DEPLOY_HOST/api/health"
    depends_on:
      - health-check
    when:
      event:
        - push
      branch:
        - main
        - master
      status:
        - success

